### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by debpedrano** [yevhenii-kanivets/Money-Tracker#163]
Greeting Project Owner,

The project is getting bigger and I think it needs a logo for a good outlook. I can make it for you if you wanted me to do so.

Thank You

-Deb

**Comment by evgenii-kanivets** [comment]
@debpedrano greetings, sorry for such a big delay with a response! I'm not sure I have smth in mind that will fit better then a current logo, but I'm not a designer at all. So if you have some bright ideas let me know :) Thanks for this message, anyway 👍

**Comment by debpedrano** [comment]
@evgenii-kanivets okay, cool! ill be sending my design as soon as its ready.

**Comment by evgenii-kanivets** [comment]
@debpedrano thanks :)

**Comment by debpedrano** [comment]
Hey i'm back, sorry for taking it too long. I am currently making your design now, thanks!

**Comment by debpedrano** [comment]
@yevhenii-kanivets 

![image](https://user-images.githubusercontent.com/40510200/48308495-6f9f3400-e5a1-11e8-941a-eab2d86742c5.png)

**Comment by yevhenii-kanivets** [comment]
@debpedrano it looks stylish, but the reason why I am not a big fan of logos with letters is that they aren't very relevant to the domain of the app. For me it looks more like maps application :)

P.S. Sorry for delayed response.

**Comment by debpedrano** [comment]
@yevhenii-kanivets I will create another design which does not include letter.

Can you answer these questions so that I can gain info about the logo.

*you don't need to answer these 4 questions

1. What is the project all about?
2. Who is the target audience of this project?
3. What does the logo need to communicate?
4. How the logo will be used?

**Comment by yevhenii-kanivets** [comment]
@debpedrano hah, the * comment is quite misleading :) But it's not difficult to answer that 4 questions anyway.
1. Money Accounting mobile application. The full description can be easily found in GP as Open Money Tracker.
2. Anybody who wants to track their expenses and incomes without paying for it and without watching ads.
3. I think, that it's a completely free personal finance tracker.
4. Just in Google Play and as an Android launcher icon.

**Comment by debpedrano** [comment]
@yevhenii-kanivets sorry for the delay and responding late, ive been busy for a week. Ill be starting making the logo basing on your answers. Thanks and have a nice day!
